### ISSUE TITLE
Recommendation to use in prod might have negative privacy implications

### ISSUE THREAD

**Issue by delroth** [andy-landy/traceback_with_variables#14]
In the current `README` for this project, I've noticed the following part:

> Should I use it after debugging is over, i.e. in production?
> Yes, of course! That way it might save you even more time.

I think that this is a dangerous advice to provide when you consider software that might be dealing with user data (e.g. serving user queries over the network, processing database entries, etc.). You could easily end up with user data or secrets being accidentally stored in the app's debug logs, and:

* Debug logs might have a different retention policy than the data would normally have (e.g. data only stored in RAM normally might end up being persisted to disk for an undefined amount of time)
* Access control policy might be more relaxed for the debug logs than for raw access to the data itself. For example, this might end up leaking a secret to a developer that might not have direct access to that secret normally (e.g. it's passed through the environment or something like that).

See https://techcrunch.com/2019/03/21/facebook-plaintext-passwords/ for a precedent which this advice could accidentally end up reproducing.

I don't have a suggested rewording, but I think the caveats should probably be made clearer to potential users of the library.

**Comment by andy-landy** [comment]
In a week I'll add
- readme notice on that issue to watch out
- filters to hide sensitive variables in a form of inclusive/exclusive (aka black/white :) ) lists 

Thanks A LOT for bringing this up.

**Comment by andy-landy** [comment]
So now there's a warning in the readme, and there are custom_var_printers which may hide the sensitive data.
